export default {
  login: "sofitanf",
  id: 59588860,
  node_id: "MDQ6VXNlcjU5NTg4ODYw",
  avatar_url: "https://avatars2.githubusercontent.com/u/59588860?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sofitanf",
  html_url: "https://github.com/sofitanf",
  followers_url: "https://api.github.com/users/sofitanf/followers",
  following_url: "https://api.github.com/users/sofitanf/following{/other_user}",
  gists_url: "https://api.github.com/users/sofitanf/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sofitanf/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sofitanf/subscriptions",
  organizations_url: "https://api.github.com/users/sofitanf/orgs",
  repos_url: "https://api.github.com/users/sofitanf/repos",
  events_url: "https://api.github.com/users/sofitanf/events{/privacy}",
  received_events_url: "https://api.github.com/users/sofitanf/received_events",
  type: "User",
  site_admin: false,
  name: "Sofita Nur Fitriana",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "intp",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2020-01-07T01:51:52Z",
  updated_at: "2020-11-24T06:44:09Z",
};
